core/myblog/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.urls import path
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('theblog/', include('theblog.urls')),
    path('', RedirectView.as_view(url='/theblog/', permanent=True)),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/theblog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('blogs/', views.BlogListView.as_view(), name='blogs'),
    path('blogs/<int:pk>', views.BlogDetailView.as_view(), name='blog-detail'),
    path('bloggers/', views.BloggerListView.as_view(), name='bloggers'),
    path('bloggers/<str:pk>', views.BloggerDetailView.as_view(), name='blogger-detail'),
]

core/theblog/models.py
from django.db import models
from django.urls import reverse

class Blog(models.Model):
    """Model representing a blog"""
    title = models.CharField(max_length=200)

    # Foreign Key used because blog can only have one author/blogger but bloggers can have multiple blogs
    # Blogger as a string rather than object because it hasn't been declaryed yet in the file
    blogger = models.ForeignKey('Blogger', on_delete=models.SET_NULL, null=True)

    summary = models.TextField(max_length=1000, help_text='Enter a brief summary of the blog post')

    date_of_blog = models.DateField(null=True, blank=True)

    post = models.TextField(max_length=5000, help_text='Start your blog post here', null=True)

    class Meta:
        ordering = ['-date_of_blog']

    def __str__(self):
        """String for representing the Model object."""
        return self.title
    
    def get_absolute_url(self):
        """Returns the url to access a more details about this blog."""
        return reverse('blog-detail', args=[str(self.id)])



class Blogger(models.Model):
    """Model representing a blog author."""
    name = models.CharField(max_length=200, help_text='Enter your username')
    location = models.CharField(max_length=100, help_text='Enter your location', null=True)
    bio = models.CharField(max_length=1000, help_text='Tell us about yourself', null=True)

    def get_absolute_url(self):
        """Returns the url to access a particular blogger instance."""
        return reverse('blogger-detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return self.name

core/theblog/views.py
from django.shortcuts import render
from theblog.models import Blog, Blogger
from django.views import generic

class BlogListView(generic.ListView):
    model = Blog
    paginate_by = 5

class BlogDetailView(generic.DetailView):
    model = Blog

class BloggerListView(generic.ListView):
    model = Blogger

class BloggerDetailView(generic.DetailView):
    model = Blogger

def index(request):
    """View function for home page of site."""

    # Generate counts of some of the main objects
    num_blogs = Blog.objects.all().count()
    num_bloggers = Blogger.objects.count()

    context = {
        'num_blogs': num_blogs,
        'num_bloggers': num_bloggers,
    }

    # Render the HTML template index.html with teh date in the context variable
    return render(request, 'index.html', context=context)

core/theblog/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
    {%block title %}<title>The Blog Site</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <!-- Add additional CSS in static file -->
    {% load static%}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-2">
            {% block sidebar %}
                <ul class="sidebar-nav">
                    <li><a href="{% url 'index' %}">Home</a></li>
                    <li><a href="{% url 'blogs' %}">All blogs</a></li>
                    <li><a href="{% url 'bloggers' %}">All bloggers</a></li>
                </ul>
            {% endblock %}
            </div>
            <div class="col-sm-10 ">{% block content %}{% endblock %}</div>
            {% block pagination %}
                {% if is_paginated %}
                    <div class="pagination">
                        <span class="page-links">
                            {% if page_obj.has_previous %}
                                <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                            {% endif %}
                            <span class="page-current">
                                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                            </span>
                            {% if page_obj.has_next %}
                                <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                            {% endif %}
                        </span>
                    </div>
                {% endif %}
            {% endblock %} 
        </div>
    </div>
</body>
</html>

core/theblog/templates/index.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>The Blog Site Home</h1>
    <p>Welcome to The Blog Site, a website developed by <em>Dan Miller</em> and <em>Mozilla Developer Network</em>!</p>
    <h2>Dynamic content</h2>
    <p>The Blog Site has the following record counts:</p>
    <ul>
        <li><strong>Blogs:</strong> {{ num_blogs }}</li>
        <li><strong>Bloggers:</strong> {{ num_bloggers }}</li>
    </ul>
{% endblock %}

core/theblog/templates/theblog/blog_detail.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Title: {{ blog.title }}</h1>

    <p><strong>Post date </strong> {{ blog.date_of_blog }}
    <p><strong>Author:</strong> <a href="{{ blog.blogger.get_absolute_url }}">{{ blog.blogger.name }}</a></p>
    <p><strong>Blog Post:</strong> {{ blog.post }}</p>

{% endblock %}

core/theblog/templates/theblog/blog_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Blog List</h>
    {% if blog_list %}
    <ul>
        {% for blog in blog_list %}
            <li>
                <a href="{{ blog.get_absolute_url }}">{{ blog.title }}</a>({{blog.date_of_blog}}) {{blog.blogger}}
            </li>
        {% endfor %}
    </ul>
    {% else %}
     <p>There are no blogs on the site.</p>
    {% endif %}
{% endblock %}

core/theblog/templates/theblog/blogger_detail.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Blogger: {{ blogger.name }}</h1>

    <p><strong>Bio </strong> {{ blogger.bio }}
   
    <!-- related manager (look up) -->
    {% if blogger.blog_set.count %}
    <h3>Blogs list</h3>
    <ul>

      {% for blog in blogger.blog_set.all %}
      <li>
        <a href="{{ blog.get_absolute_url }}">{{ blog.title }}</a> ({{blog.date_of_blog}})</a>
      </li>
      {% endfor %}

    </ul>
    {% else %}
     <p>There are no blogs by this blogger.</p>
    {% endif %}

{% endblock %}

core/theblog/templates/theblog/blogger_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Blogger List</h>
    {% if blogger_list %}
    <ul>
        {% for blogger in blogger_list %}
            <li>
                <a href="{{ blogger.get_absolute_url }}">{{ blogger.name }}</a>
            </li>
        {% endfor %}
    </ul>
    {% else %}
     <p>There are no bloggers on the site.</p>
    {% endif %}
{% endblock %}